travis:
  secure:
    BINSTAR_TOKEN: HIEOnwNRQYeehIdpa9ndeaS7N/HlfsAgDcaMmeOoyU9x1Hi8uE2CNJ1LEr9Ls1+OKoT5WxF37c8AuA24AP1tOH1niNC2m3SfseHiMSmsSJ84IJ4LDSx2bpI09e9ERQSzV0Itimy4zl94EJUvgqilaJUE0TRAbU/7+kOM6Yl0NWHCe//6P/R3xIqCaKBhcntxcmwgUpkoR7Bk6tK2zBSqN3VETiFU40NTV7lL8kokdE9NtVGZ1+PtzdRJ6i3O7R0IqNNpyDwop6h71vcDPDUzt4UC3Xi9Q/VAWyEEwDXmX66EYtDVtwWNnLZDCG2AmZYKh9lAPyDH6UnXpVOBYsb0aFFz9J4CeT95C8RWJg2Ucg8VJwwQrXAgjkmfrDMVHN81LGZDYheFy5Hnkl0g3kFKeJX7HqNdM46Vlsu4coSSBdrt4fqrXlD5cLt4ohA+pRPkJlRvcYve0eWkDbWhzm6iGuDbUrNn9ISVxgTOIeFz92X8ffz/fCRSBMs0JbV1AIHE9u7JgtFQ/3BO8rmM5CbjFn+tSk7GX02Aqbkso1jNg7i1Axk3nXZX44yad62R4j4/feGBVNoEnR8KEa7oNv2qEpPl3zErNPZeqwZ0Zp9pVAAieWMwWb/pJQArTl/UXyJxTHKzdhySw1SQ4Hp1PVwLqzRgpNY6BIc5rMJ7+E7Uo2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
