travis:
  secure:
    BINSTAR_TOKEN: CqzTVx9DUiRMVl5kYA9DdD0oJtbU0jnkbT+5n5bFe1544dhAvKZldc54IbhphwiJ3mELhAX8UnxJpXFEMHWt47G7sWFOmvq6r1ncr3usJ3F5I6tRkYvUAxR1JShwkWJ0MhxQ4nLpUw2yHYuNS3iNNsurFfUtUkdHL5QiWLO1gu8XTlGBNZQV6fjtNCSAINgxkJb4PrdsIOmkNFmZ+QyRLKpYATy8eyfAG1OKALTcQqbl61a+OC0Cz3BoMwdA714dZCscpxfQ72oJIvdFQUjK0axhu7NTDAJw1Kvo0XX9Gwpu3xCEB/6mp7+brBe0mR/deufMncAXAW78tA0qXJqVwiZ3UlceG8pKFxq0A39fWhTuZhvcul1uTdykcqCiIfCfwEj0/nYoNASxohamms2ryYX4IA8AHNY08MRl9PNBWPHxi4XOEjJk1gtv0vYNfXXc0RmUns+meleiEzIHVGdEuajX1Jk0Gl74GYiRzbAtTjx576qW4JgEeVP10FgZTYHH1WUr0Y34w6frtWrxU/gokgWfSMQnNvE6ldS4bnNGdLu5qRF3aB1URBTI3X64kpgz1+JcAMn6JC/bLO39XdJP1W+qEFNGG5hoyq81EwaWetMRTKx7e0RrlZ6utavQ7/4n+qFhyjTLw+9DHz+0FcnkX03U6MMAHs3VdDcqNRpjF/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
